version: '3'
services:
  api:
    build: ./api
    environment:
      - APPLAUSE_WEB__ENV="production"
      - APPLAUSE_WEB__FACEBOOK_USERNAME=""
      - APPLAUSE_WEB__FACEBOOK_PASSWORD=""
  app:
    build: "./app"
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - app
