version: "3"
services:
  api:
    build: ./api
    command: sh -c "./wait-for.sh redis:6379 -- python app.py"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  app:
    build: "./app"
  redis:
    image: "redis:4.0-alpine"
  scraper:
    build: "./scraper"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  web:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/applause.pw/fullchain.pem:/etc/letsencrypt/live/applause.pw/fullchain.pem
      - /etc/letsencrypt/live/applause.pw/privkey.pem:/etc/letsencrypt/live/applause.pw/privkey.pem
    depends_on:
      - api
      - app
