version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
  app:
    build: "./app"
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - app
