version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
  app:
    build: "./app"
  web:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/applause.pw/fullchain.pem:/etc/letsencrypt/live/applause.pw/fullchain.pem
      - /etc/letsencrypt/live/applause.pw/privkey.pem:/etc/letsencrypt/live/applause.pw/privkey.pem
    depends_on:
      - api
      - app
